# Uncomment this if your project is hosted on GitHub:
github_url = "https://github.com/E3SM-Project/zstash.git"

[version]
current = "1.4.2"

# Example of a semver regexp with support for PEP 440
# release candidates.Make sure this matches current_version
# before using tbump.
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)((rc\d+)?)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[file]]
src = "setup.py"

[[file]]
src = "zstash/__init__.py"

[[file]]
src = "conda/meta.yaml"

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made

#  [[before_commit]]
#  name = "check changelog"
#  cmd = "grep -q {new_version} Changelog.rst"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"
