blank_issues_enabled: true
contact_links:
    - name: Questions (zstash)
      url: https://github.com/E3SM-Project/zstash/discussions
      about: |
          Ask questions and discuss with other zstash community members here. Please
          browse the zstash Discussions Forum or zstash documentation first before asking a
          question to make sure it is not already answered. If you can't find an
          answer, please include a self-contained reproducible example with your
          question if possible. Thanks!
