name: Feature Request
description: Suggest an idea for zstash
title: "[Feature]: "
labels: []
assignees: []
body:
    - type: dropdown
      id: semver-level
      attributes:
          label: How will this affect the next version number?
          description: |
              `zstash` uses semantic versioning (https://semver.org/). Bug fixes and small improvements will increment the PATCH version. New features will increment the MINOR version. Incompatible API changes will increment the MAJOR version. The amount of work required to implement a request typically increases with each level. (For bug fixes, use the "Bug Report" template).
          multiple: false
          options:
              - Small improvement (increment PATCH version)
              - New feature (increment MINOR version)
              - Incompatibile API change (increment MAJOR version)
          default: 1
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Is your feature request related to a problem?
          description: |
              Please do a quick search of existing issues to make sure that this has not been asked before.
              Please provide a clear and concise description of what the problem is. E.g., I'm always frustrated when [...]
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Describe the solution you'd like
          description: |
              A clear and concise description of what you want to happen.
      validations:
        required: false

    - type: textarea
      id: alternatives
      attributes:
          label: Describe alternatives you've considered
          description: |
              A clear and concise description of any alternative solutions or features you've considered.
      validations:
          required: false

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: |
              Add any other context about the feature request here.
      validations:
          required: false
