name: zstash_dev
channels:
  - conda-forge
dependencies:
  # Base
  # =================
  - pip
  - python >=3.11,<3.14
  - sqlite
  - six >=1.16.0
  - globus-sdk >=3.15.0
  # Developer Tools
  # =================
  # If versions are updated, also update 'rev' in `.pre-commit.config.yaml`
  - black ==25.1.0
  - flake8 ==7.3.0
  - isort ==6.0.1
  - mypy ==1.18.2
  - pre-commit ==4.3.0
  - tbump >=6.9.0
  # Documentation
  # =================
  # If versions are updated, also update in `.github/workflows/workflow.yml`
  - jinja2 <3.1
  - sphinx >=5.2.0
  - sphinx-multiversion >=0.2.4
  - sphinx_rtd_theme >=1.0.0
  - docutils >=0.17.1
