{% set name = "zstash" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/E3SM-Project/zstash.git
  git_rev: v{{ version }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.11,<3.14
    - pip

  run:
    - python >=3.11,<3.14
    - globus-sdk=3.15.0
    - six=1.16.0
    - sqlite

test:
  imports:
    - zstash
  commands:
    - zstash --help

about:
  home: https://github.com/E3SM-Project/zstash
