{% set name = "zstash" %}
{% set version = "1.2.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/E3SM-Project/zstash.git
  git_rev: v{{ version }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - six
    - globus-sdk
    - fair-research-login

test:
  imports:
    - zstash
  commands:
    - zstash --help

about:
  home: https://github.com/E3SM-Project/zstash
