{% set name = "zstash" %}
{% set version = "1.1.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6228df2ce320b71a36d90bf0b0da08a476f184439994f767de0371f6d59c8844

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

test:
  imports:
    - zstash
  commands:
    - zstash --help

about:
  home: https://github.com/E3SM-Project/zstash
