package:
    name: zstash
    version: 0.4.0

source:
    git_url: https://github.com/E3SM-Project/zstash
    git_rev: v0.4.0

build:
    script: python setup.py install

requirements:
  build:
    - python 3
    - setuptools

  run:
    - python 3

about:
    home: https://github.com/E3SM-Project/zstash

