{% set name = "zstash" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/E3SM-Project/zstash.git
  git_rev: v{{ version }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - fair-research-login >=0.2.6,<0.3.0
    - globus-sdk >=3.0.0,<4.0.0
    - six

test:
  imports:
    - zstash
  commands:
    - zstash --help

about:
  home: https://github.com/E3SM-Project/zstash
